#!/usr/bin/env bash
# Build Path: /app/.heroku/python/

OUT_PREFIX=$1

echo "Building SQLite..."

PV='3080704'

P='sqlite-autoconf-${PV}'

SOURCE_TARBALL='http://www.sqlite.org/${P}.tar.gz'

curl $SOURCE_TARBALL | tar xz
# jx
mv $P sqlite

cd sqlite
./configure --prefix=$OUT_PREFIX
make
make install

# Cleanup
cd ..
rm -fr sqlite
